#!/bin/bash

set -eou pipefail

ROOT=$(cd $(dirname $0)/..; pwd)
source ${ROOT}/env

DOCKER_MACHINE_NAME=${DOCKER_MACHINE_NAME:-dev}
DECONST=$(docker-machine ip ${DOCKER_MACHINE_NAME})

CONTENT_STORE_URL=http://${DECONST}:9000/

if [ ${1:-} = "--stage" ] || [ ${1:-} = "-s" ]; then
  CONTENT_STORE_URL=http://${DECONST}:9001/
  shift
fi

if [ -z "${1:-}" ]; then
  cat <<EOM 1>&2
Usage: script/add-sphinx [--stage|-s] <path>

 --stage|-s - Submit content to the staging endpoint.
 path - Path to a Sphinx content repository.

EOM
  exit 1
fi

# Acquire an API key.
export CONTENT_STORE_APIKEY=$(curl -s \
  -X POST \
  -H "Authorization: deconst ${ADMIN_APIKEY}" \
  ${CONTENT_STORE_URL}keys?named=sphinx |
  python -c 'import sys, json; print json.load(sys.stdin)["apikey"]')

# If a custom CONTENT_ID_BASE is set in the environment, use it.
CONTENT_ID_ARG=
[ -n "${CONTENT_ID_BASE:-}" ] && CONTENT_ID_ARG="-e CONTENT_ID_BASE=${CONTENT_ID_BASE}"

# Run the Sphinx builder (from a Docker container) on the provided content repository.
docker run \
  --rm=true \
  -e ENVELOPE_DIR=/usr/content-repo/_build/deconst-envelopes \
  -e ASSET_DIR=/usr/content-repo/_build/deconst-assets \
  ${CONTENT_ID_ARG} \
  -v ${1}:/usr/content-repo \
  quay.io/deconst/preparer-sphinx

# Run the submitter on the generated output.
docker run \
  --rm=true \
  -e ENVELOPE_DIR=/usr/content-repo/_build/deconst-envelopes \
  -e ASSET_DIR=/usr/content-repo/_build/deconst-assets \
  -e CONTENT_SERVICE_URL=${CONTENT_STORE_URL} \
  -e CONTENT_SERVICE_APIKEY=${CONTENT_STORE_APIKEY} \
  ${CONTENT_ID_ARG} \
  -v ${1}:/usr/content-repo \
  quay.io/deconst/submitter
