#!/bin/bash

set -eou pipefail

ROOT=$(cd $(dirname $0)/..; pwd)
source ${ROOT}/env
source ${ROOT}/script/include/setup.sh

STAGING=

if [ ${1:-} = "--stage" ] || [ ${1:-} = "-s" ]; then
  STAGING=yes
  CONTENT_URL=${STAGING_CONTENT_URL}
  shift
else
  CONTENT_URL=${PROD_CONTENT_URL}
fi

if [ -z "${1:-}" ]; then
  cat <<EOM 1>&2
Usage: script/add-sphinx [--stage|-s] <path>

 --stage|-s - Submit content to the staging endpoint.
 path - Path to a Sphinx content repository.

EOM
  exit 1
fi

# Acquire an API key.
apikey sphinx ${STAGING}

# If a custom CONTENT_ID_BASE is set in the environment, use it. Otherwise, read it from your
# _deconst.json file.
if [ -z "${CONTENT_ID_BASE:-}" ]; then
  CONTENT_ID_BASE=$(python -c "import json; print json.load(open('${1}/_deconst.json'))['contentIDBase']")
fi

# Derive CONTAINER_ROOT.
if [ -z "${CONTAINER_ROOT:-}" ]; then
  CONTAINER_ROOT="$(cd ${1} && git rev-parse --show-toplevel)"
fi

# Run the Sphinx builder (from a Docker container) on the provided content repository.
docker run \
  --rm=true \
  -e ENVELOPE_DIR=${CONTAINER_ROOT}/_build/deconst-envelopes \
  -e ASSET_DIR=${CONTAINER_ROOT}/_build/deconst-assets \
  -e CONTENT_ID_BASE=${CONTENT_ID_BASE} \
  -e VERBOSE=${VERBOSE:-} \
  -e CONTENT_ROOT=${1} \
  -v ${CONTAINER_ROOT}:${CONTAINER_ROOT} \
  quay.io/deconst/preparer-sphinx

# Run the submitter on the generated output.
docker run \
  --rm=true \
  --net=${COMPOSE_NETWORK_NAME} \
  -e ENVELOPE_DIR=${CONTAINER_ROOT}/_build/deconst-envelopes \
  -e ASSET_DIR=${CONTAINER_ROOT}/_build/deconst-assets \
  -e CONTENT_SERVICE_URL=${CONTENT_URL} \
  -e CONTENT_SERVICE_APIKEY=${APIKEY} \
  -e CONTENT_ID_BASE=${CONTENT_ID_BASE} \
  -e VERBOSE=${VERBOSE:-} \
  -e CONTENT_ROOT=${1} \
  -v ${CONTAINER_ROOT}:${CONTAINER_ROOT} \
  quay.io/deconst/submitter
