#!/bin/bash

set -eou pipefail

ROOT=$(cd $(dirname $0)/..; pwd)
source ${ROOT}/env
source ${ROOT}/script/include/setup.sh

STAGING=

if [ ${1:-} = "--stage" ] || [ ${1:-} = "-s" ]; then
  STAGING=yes
  CONTENT_URL=${STAGING_CONTENT_URL}
  shift
else
  CONTENT_URL=${PROD_CONTENT_URL}
fi

if [ -z "${1:-}" ]; then
  cat <<EOM 1>&2
Usage: script/add-assets [--stage|-s] <path>

 --stage|-s - Submit assets to the staging endpoint.
 path - Path to a Deconst control repository.

EOM
  exit 1
fi

# Acquire an API key.
apikey assets ${STAGING}

# Run the asset preparer from a Docker container on the provided control repository.
exec docker run \
  --rm=true \
  --net=${COMPOSE_NETWORK_NAME} \
  -e CONTENT_STORE_URL=${CONTENT_URL} \
  -e CONTENT_STORE_APIKEY=${APIKEY} \
  -e TRAVIS_PULL_REQUEST="false" \
  -v ${1}:/var/control-repo \
  quay.io/deconst/preparer-asset
