#!/bin/bash

DECONST=$(boot2docker ip)

echo "Refreshing content map:"
echo
curl -s -i -X POST http://${DECONST}:9001/refresh

echo
echo "Refreshing layout map:"
echo
curl -s -i -X POST http://${DECONST}:9002/refresh
