#!/bin/bash

set -euo pipefail

ROOT=$(cd $(dirname $0)/..; pwd)

[ -f ${ROOT}/env ] || {
  cat <<EOM 1>&2
Environment variables not found. Please copy and customize the example file:

  cp ${ROOT}/env.example ${ROOT}/env
  \${EDITOR} ${ROOT}/env

EOM
  exit 1
}

source ${ROOT}/env

if [ -d "${CONTROL_REPO_PATH}/node_modules/grunt-deconst-assets" ]; then
    cd ${CONTROL_REPO_PATH}
    TRAVIS_PULL_REQUEST=false \
    CONTENT_STORE_URL=http://$(boot2docker ip):9000 \
    CONTENT_STORE_APIKEY=${ADMIN_APIKEY} \
    grunt deconst_assets

    cd ${ROOT}
fi

exec docker-compose restart presenter $*
